### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by Serabe** [antiwork/countdown.js#2]
Add support for using countdown.js with bower package manager.

**Comment by ColemanGariety** [comment]
+1

**Comment by kn** [comment]
Good idea. Waiting on [this issue](https://github.com/bower/bower/issues/120#issuecomment-24707169).

**Comment by kn** [comment]
:shipit: 

`bower install countdown.js`

**Comment by Serabe** [comment]
Thanks!

**Comment by lessless** [comment]
file lib/countdown.js is only 42 strings long
